kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-sc-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0e58fa2802fbe0d1e
  directoryPerms: "700"
  basePath: "/expense"